const verbs = {
    'retin': 'listen',
    'gin': 'say',
    'jẹ': 'accept',
    'di': 'let',
    'bẹ': 'beg',
    'ka': 'able',
    'bì': 'born',
    'kpe': 'call',
    'gba': 'take',
    'wà': 'come/will',
    'fẹ': 'want',
    'tse': 'do',
    'bà': 'meet',
    'gbaa': '-ing',
    'bí': 'borrow',
    'forijẹ': 'accept',
    'buru': 'meet in motion',
    'dinma': 'embrace',
    'dọ': 'marry',
    'ró': 'tie',
    'ni': 'wear',
    'dá': 'transform',
    'tó': 'reach',
    'desin': 'know',
    'jẹrun': 'eat',
    'tsọn': 'look',
    'tsitsi': 'resemble',
    'jẹ̀': 'eat',
    'la': 'lick',
    'kuro': 'finish',
    'gbe': 'carry',
    'mu gbẹ': 'give',
    'da': 'turn/throw',
    'kin': 'greet',
    'wọ': 'enter',
    'nẹ': 'have',
    'kani': 'stay',
    'lele': 'follow',
    "kó'tsi": 'return',
    'sá': 'run',
    'rè': 'go',
    'ri': 'see',
    'din': 'tie'
}

const pronouns = {
    'èyí': 'this',
    'aghan': 'they/them',
    'a': 'they/them',
    'o': 'she/he/it',
    'ain': 'she/he says',
    'mai': 'I say',
    'mi': 'me',
    'èmi': 'me',
    'mo': 'I',
    'bokọ': 'what',
    'nikọ': 'what',
    'dede': 'all',
    'wee': 'the',
    'ma': 'when',
    'ro': 'her/him',
    'wo': 'you',
    'uwọ': 'you',
    'rẹ': 'you',
    'owún': 'na him/her'
};

const adjectives_adverbs = {
    'sẹngua': 'beautiful',
    'ghele':'really',
    'gẹrẹ': 'very',
    'osan': 'okay',
    'gege': 'now',
    'bọbọ': 'some',
    'ẹyin': 'back'
}
const misc = {
    'ọkan': 'one',
    'inọ': 'inside',
    'wee': 'the',
    'sin': 'is it',
    'ti': 'that',
    'éè': 'not',
    'gha': 'where',
    'de': 'but',
    'tee': 'yet',
    'te': 'yet',
    'tsi': 'before / in the way of',
    'ni': 'in',
    'biri': 'and',
    'kì': 'any',
    'gbẹ': 'for',
    'rẹn': '',
    'máà': "don't"
}

const nouns = {
    'ọma': 'child',
    'ọmẹtiẹ': 'small child',
    'ọnobirẹn': 'woman',
    'ọnọkẹrẹn': 'man',
    'ẹye': 'world',
    'ẹgualẹ': 'snake',
    'ọjọ': 'day',
    'ubo': 'place',
    'oko': 'bush',
    'ajá': 'town',
    'obirẹn': 'wife',
    'aya': 'wife',
    'ẹsẹn': 'leg',
    'ẹwọ': 'hand',
    'origho': 'head',
    'ẹju': 'eye',
    'ẹwu': 'shirt',
    'aṣọ': 'cloth',
    'isabatu': 'shoe',
    'ọkpa': 'walking stick',
    'ẹkoro': 'cap',
    'uwẹrẹ': 'there',
    'iyẹ': 'mother',
    'ọwa': 'father',
    'ọkọ': 'husband',
    'ara': 'body',
    'ọjẹ': 'food',
    'abẹtẹ': 'room',
    'irẹye': 'person',
    'ulí': 'house',
    'orun': 'nights',
    'ana': 'in law',
    'ẹrun': 'properties',
    'ọl-': 'owner (of)',
    'alẹ': 'ground',
    'oribiti': 'Boa'
}

const allWords = { ...verbs, ...pronouns, ...nouns, ...misc, ...adjectives_adverbs };
export { verbs, pronouns, nouns, misc, adjectives_adverbs, allWords };