const verbs = {
    'retin': 'listen',
    'gin': 'say',
    'jẹ': 'accept',
    'forijẹ': 'accept',
    'di': 'let',
    'bì': 'born',
    'gba': 'take',
    'wà': 'come/will',
    'fẹ': 'want',
    'tse': 'do',
    'bà': 'meet',
    'gbaa': '-ing',   
    'dọ': 'marry',
    'ni': 'wear',
    'dá': 'transform',
    'tsitsi': 'resemble',
    'jẹ̀': 'eat',
    'gbe': 'carry',
    'da': 'turn/throw',
    'kin': 'greet',
    'wọ': 'enter',
    'ri': 'see',
    'din': 'tie',
    'mu-ni': 'put',
    'gbo': 'hear'
}

const verbsTwo = {
    'bẹ': 'beg',
    'buru': 'meet in motion',
    'dinma': 'embrace',
    'tsọn': 'look',
    'lele': 'follow',
    "kó'tsi": 'return',
    'sá': 'run',
    'rè': 'go',
    'kuro': 'finish',
    'desin': 'know',
    'tó': 'reach',
    'nẹ': 'have',
    'bí': 'borrow',
    'bọ': 'loosen',
    'mu gbẹ': 'give',
    'jẹrun': 'eat',
    'la': 'lick',
    'kani': 'stay',
    'ró': 'tie',
    'kpe': 'call',
    'gbe-tsi': 'carry into',
    'sọn': 'cried',
    'sọkun': 'cry',
    'lù': 'ring',
    'sa': 'ran',
    'tsibu': 'fell'
}

const pronouns = {
    'èyí': 'this',
    'aghan': 'they/them',
    'a': 'they/them',
    'o': 'she/he/it',
    'ain': 'she/he says',
    'mai': 'I say',
    'mi': 'me',
    'èmi': 'me',
    'mo': 'I',
    'bokọ': 'what',
    'nikọ': 'what',
    'dede': 'all',
    'wee': 'the',
    'ma': 'when',
    'ro': 'her/him',
    'wo': 'you',
    'uwọ': 'you',
    'rẹ': 'you',
    'owún': 'na him/her'
};

const adjectivesAdverbs = {
    'sẹngua': 'beautiful',
    'ghele':'really',
    'gẹrẹ': 'very',
    'osan': 'okay',
    'gege': 'now',
    'bọbọ': 'some',
    'ẹyin': 'back',
    'ọrọnrọn': 'better',
    'kẹkẹkẹkẹ': 'consistently'
}
const misc = {
    'ọkan': 'one',
    'inọ': 'inside',
    'wee': 'the',
    'sin': 'is it',
    'ti': 'that',
    'éè': 'not',
    'gha': 'where',
    'de': 'but',
    'tee': 'yet',
    'te': 'yet',
    'tsi': 'before',
    'tsi-ale': 'towards ground',
    'ni': 'in',
    'biri': 'and',
    'kì': 'any',
    'gbẹ': 'for',
    'máà': "don't",
    'kuri': 'from'
}

const nouns = {
    'ọ́má': 'child',
    'ọnobirẹn': 'woman',
    'ọnọkẹrẹn': 'man',
    'ẹye': 'world/life',
    'ẹgualẹ': 'snake',
    'ọjọ': 'day',
    'obirẹn': 'wife',
    'aya': 'wife',
    'ẹsẹn': 'leg',
    'ẹwọ': 'hand',
    'omere': 'brother',
    'ẹju': 'eye',
    'aṣọ': 'cloth',
    'isabatu': 'shoe',
    'ọkpa': 'walking stick',
    'iyẹ': 'mother',
    'ọwa': 'father',
    'ọkọ': 'husband',
    'ọjẹ': 'food',
    'ulí': 'house',
    'ana': 'in law',
    'alẹ': 'ground',
    'oribiti': 'Boa',
    'urun': 'thing'
}

const nounsTwo = {
    'origho': 'head',
    'ubo': 'place',
    'orun': 'nights',
    'uwẹrẹ': 'there',
    'irẹye': 'person',
    'abẹtẹ': 'room',
    'ẹkoro': 'cap',
    'ọ̀mà': 'bell',
    'ajá': 'town',
    'oko': 'bush',
    'ẹwu': 'shirt',
    'ara': 'body',
    'ẹrun': 'properties',
    'ọmẹtiẹ': 'small child',
    'ọl-': 'owner (of)',
    'ubọwe': 'here',
    'obobo': 'plantain',
    'egin': 'tree'
}
const allWords = { ...verbs, ...pronouns, ...nouns, ...misc, ...adjectivesAdverbs, ...verbsTwo, ...nounsTwo };
export { verbs, pronouns, nouns, misc, adjectivesAdverbs, verbsTwo, nounsTwo, allWords };