const verbs = {
    'retin': 'listen',
    'gin': 'say',
    'jẹ': 'accept',
    'di': 'let',
    'bẹ': 'beg',
    'ka': 'able',
    'bì': 'born',
    'kpe': 'call',
    'gba': 'take',
    'wa': 'come/will',
    'fẹ': 'want',
    'tse': 'do',
    'bà': 'meet',
    'gba-a': '-ing',
    'bí': 'borrow',
    'forijẹ': 'agree',
    'buru': 'meet in motion',
    'dinma': 'embrace (romantically)',
    'dọ': 'marry',
    'ró': 'tie',
    'ni': 'wear', // add accent,
    'dá': 'transform',
    'tó': 'reach',
    'desin': 'know',
    'jẹrun': 'eat',
    'tsọn': 'look',
    'tsitsi': 'resemble',
    'jẹ̀': 'eat',
    'la': 'lick',
    'kuro': 'finish',
    'gbe': 'carry',
    'mu gbẹẹ': 'give',
    'da': 'turn/throw',
    'kin': 'greet',
    'wọ': 'enter',
    'nẹ': 'have'
}

const pronouns = {
    'èyí': 'this',
    'aghan': 'they',
    'a': 'they',
    'o': 'she/he',
    'ain': 'she/he says',
    'mai': 'I say',
    'mi': 'me',
    'èmi': 'me',
    'mo': 'I',
    'bokọ': 'what',
    'nikọ': 'what',
    'dede': 'all',
    'wee': 'the',
    'ma': 'when',
    'ro': 'her/him',
    'wo': 'you'
};

const adjectives_adverbs = {
    'sẹngua': 'beautiful',
    'ghele':'really',
    'do': 'very',
    'san': 'okay'
}
const misc = {
    'ọkan': 'one',
    'inọ': 'inside',
    'wee': 'the',
    'sin': 'is it',
    'ti': 'that',
    'wen': 'not',
    'éè': 'not',
    'gha': 'where',
    'de/derekede': 'but',
    'tee': 'yet',
    'te': 'yet',
    "t'a": "that they",
    "t'o": "that he/she",
    'tsi': 'before',
    'ni': 'in',
    'biri': 'and'
}

const nouns = {
    'ọma': 'child',
    'ọmẹtiẹ': 'small child',
    'ọnobirẹn': 'woman',
    'ọnọkẹrẹn': 'man',
    'ẹye': 'world',
    'ẹgualẹ': 'snake',
    'ọjọ': 'day',
    'ubo': 'place',
    'oko': 'bush',
    'ajá': 'town',
    'obirẹn': 'wife',
    'ẹsẹn': 'leg',
    'ẹwọ': 'hand',
    'origho': 'head',
    'ẹju': 'eye',
    'ẹwu': 'shirt',
    'aṣọ': 'cloth',
    'isabatu': 'shoe',
    'ọkpa': 'walking stick',
    'ẹkoro': 'cap',
    'uwẹre': 'there',
    'iyẹ': 'mother',
    'ọwa': 'father',
    'ọkọ': 'husband',
    'ara': 'body',
    'ọjẹ': 'food',
    'abẹtẹ': 'room',
    'irẹye': 'person'
}

const allWords = { ...verbs, ...pronouns, ...nouns, ...misc, ...adjectives_adverbs };
export { verbs, pronouns, nouns, misc, adjectives_adverbs, allWords };